### ISSUE TITLE
what is this repository for?

### ISSUE THREAD

**Issue by afeld** [18F/slack-export-handling#4]
...a visitor may ask themselves 😄 @tbaxter-18f @wslack

**Comment by wslack** [comment]
Good point! Sometimes there are occasions when a Slack export needs to be searched. For example, there might be need to find a record of a conversation between former employees.

Slack already includes a way to export all records, but there's no way to search those exports. In order to make a search process quick (and to avoid reading more records than needed), we created this tool.

**Comment by afeld** [comment]
You might want to put that at the top of the README, is kinda what I was getting at 😉

**Comment by wslack** [comment]
https://github.com/18F/slack-export-handling/commit/4c7977f4c68ecd8bf8ac62e4a82ed918bb280d48

❤️ (may I close?)
